# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yari Labs
email: hexlxlo@xyxaxrxixlxaxbxs.com
pgp: TO BE SET IF SO
slogan: Technology Supercharged
masthead: Software | Consulting | Coaching.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yarilabs.com" # the base hostname & protocol for your site
logo: assets/img/lightrains-logo.png

twitter_username: yarilabs
github_username:  yarilabs
gplus: https://plus.google.com/TOBESET
address: Rua dos Capelistas, 30 3.ยบ Andar, Sala I
phone:  351 253 776 740

# Build settings
maRkdown: kramdown
permalink: :title

# Handling Reading
safe:         false
exclude:      [
  ".git",
  ".svn",
  "assets/semantic",
  "node_modules",
  "gulpfile.js",
  "semantic.json",
  "package.json",
  "README.md",
  "assets/raw",
  ".gulp-scss-cache",
  "assets/css/lightbox.min.css",
  "assets/css/main.css",
  "assets/css/main.scss",
  "assets/css/semantic.css",
  "assets/css/semantic.min.css",
  "assets/js/isotope.pkgd.js",
  "assets/js/jquery.min.js",
  "assets/js/lightbox.min.js",
  "assets/js/lightbox.min.map",
  "assets/js/semantic.js",
  "assets/js/site.js"
]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-admin

paginate: 8
paginate_path: "/blogs/page:num/"
tag_page_dir: tag
tag_feed_dir: tag
tag_page_layout: tag_page
tag_feed_layout: tag_feed

social: [ "https://twitter.com/yarilabs", "https://www.facebook.com/yarilabs", "https://plus.google.com/TOBESET", "http://www.linkedin.com/company/11137193", "https://play.google.com/store/apps/developer?id=Yari+Labs+Ltd", "https://foursquare.com/v/TOBESET", "https://www.youtube.com/channel/WHATSTHATCHANNEL", "http://www.acquia.com/partners/showcase/lightrains-technolabs-pvt-ltd", "https://github.com/yarilabs"]

compress_html:
  clippings: [div, p, ul, td, h1, h2]
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: [local]
  blanklines: true
  profile: false
  startings: []

ampdir: amp
