# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yari Labs
email: hello@yarilabs.com
pgp:
slogan:
masthead: "Software <i class=\"ellipsis vertical icon\"></i> Consulting <i class=\"ellipsis vertical icon\"></i> Coaching"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.yarilabs.com" # the base hostname & protocol for your site
logo: /assets/img/yarilabs-logo.svg

twitter_username: yarilabs
github_username:  yarilabs
googlemap: https://goo.gl/maps/RLpub52RD8H2

address: Rua dos Capelistas, 30 3rd Floor | 86-90 Paul Street, 3rd Floor, London, United Kingdom, EC2A 4NE
phone:  351 253776740
ukphone: 44 7445007797

# Build settings
maRkdown: kramdown
permalink: :title

# Handling Reading
safe:         false
exclude:      [
  ".git",
  ".svn",
  "assets/semantic",
  "node_modules",
  "gulpfile.js",
  "semantic.json",
  "package.json",
  "README.md",
  "assets/raw",
  ".gulp-scss-cache",
  "assets/css/lightbox.min.css",
  "assets/css/main.css",
  "assets/css/main.scss",
  "assets/css/semantic.css",
  "assets/css/semantic.min.css",
  "assets/js/isotope.pkgd.js",
  "assets/js/jquery.min.js",
  "assets/js/lightbox.min.js",
  "assets/js/lightbox.min.map",
  "assets/js/semantic.js",
  "assets/js/site.js"
]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-admin

paginate: 8
paginate_path: "/blogs/page:num/"
tag_page_dir: tag

tag_feed_dir: tag
tag_page_layout: tag_page
tag_feed_layout: tag_feed

social: [ "https://twitter.com/yarilabs", "https://www.facebook.com/yarilabs", "https://plus.google.com/111792819110493287001/about", "https://www.linkedin.com/company/yarilabs", "https://play.google.com/store/apps/developer?id=Yari+Labs+Ltd", "", "https://www.youtube.com/channel/UCrO53DBguJlnmbWZaXo2kvg", "https://github.com/yarilabs"]

compress_html:
  clippings: [div, p, ul, td, h1, h2]
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: [local]
  blanklines: true
  profile: false
  startings: []

ampdir: amp
