mv about/careers.html  about/careers
mv about/contact.html about/contact
mv about/portfolio.html about/portfolio
mv about/technology.html about/technology
mv about/yarilabs.html about/yarilabs
mv careers/elixir-developer.html careers/elixir-developer
mv careers/internship.html careers/internship
mv careers/javascript-engineers.html careers/javascript-engineers
mv consulting/company-consulting.html consulting/company-consulting
mv consulting/product-development.html consulting/product-development
